---
title: "Voronoi diagram"
author: "Xènia Casanovas Díez"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load-packages, include = FALSE}

if(!require(tidyverse)){
  install.packages("tidyverse")
  library(tidyverse)
}

if(!require(ggvoronoi)) {
  install.packages("ggvoronoi")
  library(ggvoronoi)
}

if(!require(plotly)) {
  install.packages("plotly")
  library(plotly)
}

if(!require(htmlwidgets)) {
  install.packages("htmlwidgets")
  library(htmlwidgets)
}

```

```{r, include = FALSE}
nuclearWeapons <- read.csv2("nuclearWeapons.csv")
names(nuclearWeapons) <- c("country", "latitude", "longitude", "totalWeapons", "activelyDeployed", "available", "retired")
```


```{r}
worldMap <- ggplot2::map_data('world')
names(worldMap) <- c("longitude","latitude", "group","order","region","subregion")

outline.df <- data.frame(x = c(-180.0000, 190.2708, 190.2708, -180.0000),
                         y = c(-85.19218, -85.19218, 83.59961, 83.59961))

voronoiDiagram <- ggplot(nuclearWeapons, aes(x = longitude, y = latitude, fill = available)) +
  theme_void() +
  geom_polygon(data = worldMap, aes(group = group), fill="#ffffff", color="#000000", size = 0.05) +
  geom_voronoi(outline = outline.df, alpha = .5) +
  geom_path(stat="voronoi", outline = outline.df, size=0.1, color="white") +
  # geom_point(color = "#ffffff", alpha = .5) + 
  geom_text(label = nuclearWeapons$country, check_overlap = TRUE, size = 3, vjust = -1) +
  scale_fill_gradient(low = "#729dc5", high = "#2d3e4e") +
  coord_quickmap() +
  labs(title="Voronoi Diagram Nuclear Weapons Worldwide")

voronoiDiagram
#ggsave("voronoiDiagram.png")
saveWidget(ggplotly(voronoiDiagram, tooltip = c("available")), file = "voronoiDiagram.html")
```


